services:
  sfu:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    ports:
      - "7000:7000"
      - "5000-5200:5000-5200/udp"
    volumes:
      - ./sfu.toml:/configs/sfu.toml:ro
    environment:
      - PION_LOG_TRACE=sfu
